title: "Thanox"
remote_theme: just-the-docs/just-the-docs

theme: jekyll-theme-cayman

plugins:
  - jekyll-polyglot

  # jekyll-polyglot
languages: ["en", "zh"]
default_lang: "en"
exclude_from_localization:
  - "assets/images"
parallel_localization: true
sass: # https://github.com/untra/polyglot/issues/107#issuecomment-598274075
  sourcemap: never
